const userTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_ERROR: 'SIGN_UP_ERROR',
  RESSET_PASSWORD_SUCCESS: 'RESSET_PASSWORD_SUCCESS',
  RESSET_PASSWORD_ERROR: 'RESSET_PASSWORD_ERROR',
  RESSET_AUTH_FORMS: 'RESSET_AUTH_FORMS',
};

export default userTypes;
